imdb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="home"),
    path('add_movie', views.add_movie, name="add_movie"),
    path('delete_movie/<movie_id>', views.delete_movie, name="delete_movie"),
    path('edit_movie/<movie_id>', views.edit_movie, name="edit_movie"),
    path('actors', views.actors, name="actors"),
    path('add_actor', views.add_actor, name="add_actor"),
    path('delete_actor/<actor_id>', views.delete_actor, name="delete_actor"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imdbproject/urls.py
from django.contrib import admin
from django.urls import path, include
from imdb import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imdb.urls')),
]

imdb/models.py
from django.db import models
from django.contrib import admin
# Create your models here.
class ActorList(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=6, choices=(('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')))
    bio = models.TextField(blank=False)
    birthdate = models.DateField()
    
    class Meta:
        ordering = ('name',)

    def __str__(self):
        return (self.name)

class MovieList(models.Model):
    title = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField()
    plot = models.TextField()
    actor = models.ManyToManyField(ActorList, related_name='Actor', through='Roles', verbose_name='ACTOR/ACTRESS')
    poster = models.ImageField(upload_to='movie_poster', blank= True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

class Roles(models.Model):
    role_name = 'Actor'
    actor = models.ForeignKey(ActorList, on_delete=models.CASCADE, verbose_name='SELECT ACTOR')
    movie = models.ForeignKey(MovieList, on_delete=models.CASCADE, verbose_name='SELECT MOVIE')

    class Meta:
        verbose_name = 'Role'
        verbose_name_plural = 'Roles'
        auto_created = True

    def __str__(self):
        return self.role_name

class roles_inline(admin.TabularInline):
    model = Roles
    extra = 1

class movieAdmin(admin.ModelAdmin):
    inlines = (roles_inline,)

imdb/forms.py
from django import forms
from .models import MovieList, ActorList

class MovieListForm(forms.ModelForm):
    class Meta:
        model = MovieList
        fields = ["title", "year", "plot", "actor", "poster"]

class ActorListForm(forms.ModelForm):
    class Meta:
        model = ActorList
        fields = ["name", "gender", "birthdate", "bio"]

imdb/views.py
from django.shortcuts import render, redirect
from .models import MovieList, ActorList
from .forms import MovieListForm, ActorListForm
import re
import datetime
import time



# Date Time
today = time.strftime(r"%m/%d/%Y %H:%M:%S", time.localtime())
today = datetime.datetime.strptime(today, '%m/%d/%Y %H:%M:%S')


# Create your views here.
def home(request):
    all_items = MovieList.objects.all()
    all_actors = ActorList.objects.all()
    return render(request, 'index.html', {'all_items' : all_items, 'all_actors': all_actors})

def add_movie(request):
    form = MovieListForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            #Validations
            title = request.POST['title']
            year = int(request.POST['year'])
            plot = request.POST['plot']
            words = title.split(' ')
            if len(words)  > 1:
                for word in words:
                    if (re.search('^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$', word) == None):
                        titleerror = 'Title can only contain Alphanumerics and Hyphen'
                        return render(request, 'add_movie.html', {'titleerror': titleerror, 'form': form, 'title': title, 'year': year, 'plot': plot})
            else:
                if (re.search('^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$', title) == None):
                    titleerror = 'Title can only contain Alphanumerics and Hyphen'
                    return render(request, 'add_movie.html', {'titleerror': titleerror, 'form': form, 'title': title, 'year': year, 'plot': plot})
            if year > 2050:
                yearerror = 'This is too far, You can not add movie after 2050'
                return render(request, 'add_movie.html', {'yearerror': yearerror, 'form': form, 'title': title, 'year': year, 'plot': plot})
            elif year < 1888:
                yearerror = 'No Movie was made before 1888'
                return render(request, 'add_movie.html', {'yearerror': yearerror, 'form': form, 'title': title, 'year': year, 'plot': plot})
            else:
                form.save()
                all_items = MovieList.objects.all()
                all_actors = ActorList.objects.all()
                return render(request, 'index.html', {'all_items': all_items, 'all_actors': all_actors})

    else:
        all_actors = ActorList.objects.all()
        return render(request, 'add_movie.html', { 'all_actors': all_actors, 'form':form })

def delete_movie(request, movie_id):
    movie = MovieList.objects.get(pk= movie_id)
    movie.delete()
    return redirect('home')

def edit_movie(request, movie_id):
    movie = MovieList.objects.get(pk= movie_id)
    form = MovieListForm(request.POST or None, request.FILES or None, instance=movie)
    if request.method == 'POST':
        if form.is_valid():
            #Validations
            title = request.POST['title']
            year = int(request.POST['year'])
            words = title.split(' ')
            if len(words) > 1:
                for word in words:
                    if (re.search('^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$', word) == None):
                        titleerror = 'Title can only contain Alphanumerics and Hyphen'
                        return render(request, 'edit_movie.html', {'movie': movie, 'titleerror': titleerror, 'form': form})
            else:
                if ( re.search('^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$', title) == None):
                    titleerror = 'Title can only contain Alphanumerics and Hyphen'
                    return render(request, 'edit_movie.html', {'movie': movie, 'titleerror': titleerror, 'form': form})
            if year > 2050:
                yearerror = 'This is too far, You can not add movie after 2050'
                return render(request, 'edit_movie.html', {'movie': movie,'yearerror': yearerror, 'form': form})
            elif year < 1888:
                yearerror = 'No Movie was made before 1888'
                return render(request, 'edit_movie.html', {'movie': movie, 'yearerror': yearerror, 'form': form})
            else:
                form.save()
                all_items = MovieList.objects.all
                all_actors = ActorList.objects.all
                return render(request, 'index.html', {'all_items': all_items, 'all_actors': all_actors})
    else:
        return render(request, 'edit_movie.html', {'movie': movie, 'form': form})

def actors(request):
        all_actors = ActorList.objects.all
        return render(request, 'actors.html', {'all_actors': all_actors})

def delete_actor(request, actor_id):
        actor = ActorList.objects.get(pk=actor_id)
        actor.delete()
        return redirect('actors')


def add_actor(request):
    if request.method == 'POST':
        form = ActorListForm(request.POST or None)
        if form.is_valid():
            # Validation
            dob = request.POST['birthdate']
            dobfull = (dob + ' 00:00:00')
            dobfull = datetime.datetime.strptime(dobfull, '%Y-%m-%d %H:%M:%S')
            bio = request.POST['bio']
            name = request.POST['name']
            words = name.split(' ')
            if len(words) > 1:
                for word in words:
                    if (re.search('^[a-zA-Z]+$', word) == None):
                        nameerror = 'Name can only contain Alphabets'
                        return render(request, 'add_actor.html', {'nameerror': nameerror, 'form': form, 'name': name, 'dob': dob, 'bio': bio})
            else:
                if (re.search('^[a-zA-Z]+$', name) == None ):
                    nameerror = 'Name can only contain Alphabets'
                    return render(request, 'add_actor.html', {'nameerror': nameerror, 'form': form, 'name': name, 'dob': dob, 'bio': bio})
            if dobfull > today:
                doberror = 'Date of Birth can not be in future'
                return render(request, 'add_actor.html', {'doberror': doberror, 'form': form, 'name': name, 'dob': dob, 'bio': bio})
            else:
                form.save()
                all_actors = ActorList.objects.all
                return render(request, 'actors.html', {'all_actors': all_actors})

    else:
        return render(request, 'add_actor.html', {})

imdb/templates/actors.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row makegap">
        <div class="col-sm-2"></div>
        <div class="col-sm-2">All Actors</div>
        <div class="col-sm-4"></div>
        <div class="col-sm-2"><a class="btn btn-primary" href="{% url 'add_actor' %}">Add Actor</a></div>
    </div>
    <div class="makegap"></div>
    {% if all_actors %}
        {% for actor in all_actors %}
            <div class="makegap"></div>
            <div class="row text-center">
                <div class="col-sm-12"><h2 class="title">{{actor.name}}</h2></div>
            </div>

            <div class="row text-center text-muted">
                <div class="col-sm-12"><h6>Date of Birth: {{actor.birthdate}}</h6></div>
            </div>

            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-1"><p><b>Gender:</b></p></div>
                <div class="col-sm-6"><p class="justify">{{actor.gender}}</p></div>
            </div>

            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-1"><p><b>Biography:</b></p></div>
                <div class="col-sm-6"><p class="justify">{{actor.bio}}</p></div>
            </div>

            <div class="row">
                <div class="col-sm-7"></div>
                <div class="col-sm-3"><a class="btn btn-danger" href="{% url 'delete_actor' actor.id %}">Delete Actor</a></div>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

imdb/templates/add_actor.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form class="form needs-validation" method="POST">
{% csrf_token %}
<div class="makegap"></div>
<div class="container">
    <div class="form-group form-row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <label for="name">Actor Name</label>
            <input type="text" id="name" class="form-control" name="name" value="{{name}}" placeholder="Tom Cruise" required>
            <small class="errorclass">{{nameerror}}</small>
        </div>
    </div>
    <div class="form-inline form-group form-check text-center form-row">
        <div class="col-sm-4"></div>
        <div class="col-sm-1">
        Gender:
        </div>
        <div class="col-sm-1">
            Male <input class="form-check-input" type="radio" name="gender" value="Male" checked>
        </div>
        <div class="col-sm-1">
            Female <input class="form-check-input" type="radio" name="gender" value="Female">
        </div>
        <div class="col-sm-1">
            Others <input class="form-check-input" type="radio" name="gender" value="Others">
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <label for="birthdate">Date of Birth</label>
            <input class="form-control" name="birthdate" id="birthdate" type="date" value="{{dob}}" required>
            <small class="errorclass">{{doberror}}</small>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <label for="bio">Bio</label>
            <textarea required name="bio" id="bio" rows=4 class="form-control" placeholder="Write a short Bio Here.....">{{bio}}</textarea>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-6"></div>
        <div class="col-sm-4">
            <a class="btn btn-secondary" href="{% url 'actors' %}">Cancel</a>
            <button type="submit" class="btn btn-primary" type="submit">Add Actor</button>
        </div>
    </div>
</div>
</form>

{% endblock %}

imdb/templates/add_movie.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="makegap"></div>
    <div class="row text-center">
        <div class="col-sm-12">
            <h2>Add New Movie</h2>
        </div>
    </div>
    <form name="MovieListForm" class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group form-row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <label for="movietitle">Title of the Movie</label>
                <input required class="form-control" type="text" placeholder="Write the movie name...." name="title" id="movietitle" value="{{title}}">
                <small class="errorclass">{{titleerror}}</small>
            </div>
        </div>
        <div class="form-group form-row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <label for="movieyear">Release Year</label>
                <input required class="form-control" type="number" placeholder="2018" name="year" id="movieyear" value="{{year}}">
                <small class="errorclass">{{yearerror}}</small>
            </div>
        </div>
        <div class="form-group form-row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <label for="movieplot">Plot</label>
                <textarea required class="form-control" name="plot" id="movieplot" rows=4 placeholder=" Big Plot Here..." >{{plot}}</textarea>
            </div>
        </div>

        <div class="form-group form-row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
            <label for="id_actor">Select Movie Cast</label>
            <small id="actortip" class="form-text text-muted">You can select Multiple Cast by Holding Ctrl/Cmd</small>
                <div aria_describedby="actortip">{{ form.actor|safe }}</div>
            </div>
        </div>
        <div class="form-group form-row">
          <div class="col-sm-2"></div>
          <div class="col-sm-8">
            <small class="form-text text-muted">You can only upload an image file.</small>
            <div class="upload-btn-wrapper">
              <button class="uploadbtn">Upload Poster</button>
            {{ form.poster }}
            </div>
          </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Add Movie</button>
                <a class="btn btn-secondary" href="{% url 'home' %}">Cancel</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

imdb/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Personal CSS -->
    <link rel='stylesheet' href="{% static 'css/main.css' %}?{% now "U" %}" type="text/css" />

    <title>IMDB App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">I M D B</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Movies<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'actors' %}">Actors</a>
            </li>

            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

imdb/templates/edit_movie.html
{% extends "base.html" %}
{% load static %}
{% block content %}
   {% if movie %}

    <div class="container">
        <div class="makegap"></div>
        <div class="row text-center">
            <div class="col-sm-12">
                <h2>Edit Movie</h2>
            </div>
        </div>
        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group form-row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <label for="movietitle">Title of the Movie</label>
                    <input required class="form-control" type="text" placeholder="{{movie.title}}" name="title" id="movietitle" value="{{movie.title}}">
                    <small class="errorclass">{{titleerror}}</small>
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <label for="movieyear">Release Year</label>
                    <input required class="form-control" type="number" placeholder="{{movie.year}}" name="year" id="movieyear" min=1950 max=2019 value="{{movie.year}}">
                    <small class="errorclass">{{yearerror}}</small>
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <label for="movieplot">Plot</label>
                    <textarea required class="form-control" name="plot" id="movieplot" rows=4 placeholder="{{movie.plot}}">{{movie.plot}}</textarea>
                </div>
            </div>

            <div class="form-group form-row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                <label for="id_actor">Select Movie Cast</label>
                <small id="actortip" class="form-text text-muted">You can select Multiple Cast by Holding Ctrl/Cmd</small>
                    <div>{{ form.actor|safe }}</div>
                </div>
            </div>
            <div class="form-group form-row">
              <div class="col-sm-2"></div>
              <div class="col-sm-8">
                <small class="form-text text-muted">You can only upload an image file.</small>
                <div class="upload-btn-wrapper">
                  <button class="uploadbtn">Upload Poster</button>
                {{ form.poster }}
                </div>
              </div>
            </div>
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Done</button>
                    <a class="btn btn-secondary" href="{% url 'home' %}">Cancel</a>
                </div>
            </div>
        </form>
    </div>
    {% endif %}

{% endblock %}

imdb/templates/index.html
{% extends 'base.html' %}}
{% block content %}
<div class="row makegap">
    <div class="col-sm-2"></div>
    <div class="col-sm-2">All Movies</div>
    <div class="col-sm-4"></div>
    <div class="col-sm-2"><a class="btn btn-primary" href="{% url 'add_movie' %}">Add Movie</a></div>
</div>
<div class="makegap"></div>

{% if all_items %}
    {% for movie in all_items %}
        <div class="makegap"></div>
        <div class="row">
          <div class="col-sm-2"></div>
          <div class="col-sm-3">
            {% if movie.poster %}
              <img src="{{movie.poster.url}}" width="250"/>
            {% endif %}
          </div>
          <div class="col-sm-7">
            <div class="row">
                <div class="col-sm-12"><h2 class="title">{{movie.title}}</h2></div>
            </div>

            <div class="row">
                <div class="col-sm-12"><h5>Release Year: {{movie.year}}</h5></div>
            </div>

            <div class="row text-center">
                <div class="col-sm-1"><p><b>PLOT:</b></p></div>
                <div class="col-sm-6"><p class="justify">{{movie.plot}}</p></div>
            </div>

            <div class="row text-center">
                <div class="col-sm-1"><p><b>CAST:</b></p></div>

                <div class="col-sm-6">
                  <p class="justify">
                    {% for actor in movie.actor.all %}
                      {{ actor.name }},
                    {% endfor %}
                  </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-4"><a class="btn btn-warning" href="{% url 'edit_movie' movie.id %}">Edit Movie</a> </div>
                <div class="col-sm-4"><a class="btn btn-danger" href="{% url 'delete_movie' movie.id %}">Delete Movie</a></div>
            </div>
          </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}